name: Test unreleased Django
on:
  schedule:
    - cron: '30 10 * * 1-5'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test latest stable Python with unreleased Django
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.cfg') }}
          restore-keys: ${{ runner.os }}-pip
      - name: Install dependencies
        run: |
          pip install --upgrade https://github.com/django/django/archive/main.tar.gz
          pip install --upgrade -r test-requirements.txt
          pip install .
      - name: Run tests
        run: make docker-up && coverage run -m pytest -svv --speedtest
